### PR TITLE
MaxDate next month button fix

### PR DESCRIPTION
**Pull request by rfuhrer**
Fixed an issue where the next month button would always be hidden when a maxdate was set.  The logic needs to be the opposite for a mindate vs maxdate however it was attempting to use the same function for both

### CODE REVIEW

**Comment by SimeonC** [comment]
Ah, Nice catch. For future reference - can you edit the files in the `src` folder not the `dist` folder as the the file you edited is actually a compiled file so it'll get overwritten. (Also it's really hard to spot the changes to the templates in this view).

**Comment by rfuhrer** [comment]
I pushed another commit.  This time it's at least 10% more better :)

**Comment by SimeonC** [comment]
Awesome, thanks. I'll get this merged in later.

**Comment by SimeonC** [comment]
Apologies for the delay - got a heap of work and forgot about it. I'm finding some time to work on this soon.

**Pull request merged**
